config/routes.rb
Sessions::Application.routes.draw do
  resources :locations

  resources :boards

  resources :kites

  resources :sessions

  get "home/index"

  devise_for :users, skip_helpers: true 

  root :to => 'home#index'

end

app/models/kite.rb
class Kite < ActiveRecord::Base
  belongs_to :user
  has_many :sessions
  
  validates :name, presence: true
end

app/controllers/kites_controller.rb
class KitesController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /kites
  # GET /kites.json
  def index
    @kites = current_user.kites.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @kites }
    end
  end

  # GET /kites/1
  # GET /kites/1.json
  def show
    @kite = current_user.kites.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @kite }
    end
  end

  # GET /kites/new
  # GET /kites/new.json
  def new
    @kite = current_user.kites.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @kite }
    end
  end

  # GET /kites/1/edit
  def edit
    @kite = current_user.kites.find(params[:id])
  end

  # POST /kites
  # POST /kites.json
  def create
    @kite = current_user.kites.new(params[:kite])

    respond_to do |format|
      if @kite.save
        format.html { redirect_to @kite, notice: 'Kite was successfully created.' }
        format.json { render json: @kite, status: :created, location: @kite }
      else
        format.html { render action: "new" }
        format.json { render json: @kite.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /kites/1
  # PUT /kites/1.json
  def update
    @kite = current_user.kites.find(params[:id])

    respond_to do |format|
      if @kite.update_attributes(params[:kite])
        format.html { redirect_to @kite, notice: 'Kite was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @kite.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kites/1
  # DELETE /kites/1.json
  def destroy
    @kite = current_user.kites.find(params[:id])
    @kite.destroy

    respond_to do |format|
      format.html { redirect_to kites_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/kites_helper.rb
module KitesHelper
end

app/views/kites/_form.html.haml
= form_for @kite do |f|
  -if @kite.errors.any?
    #error_explanation
      %h2= "#{pluralize(@kite.errors.count, "error")} prohibited this kite from being saved:"
      %ul
        - @kite.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/kites/edit.html.haml
%h1 Editing kite

= render 'form'

= link_to 'Show', @kite
\|
= link_to 'Back', kites_path

app/views/kites/index.html.haml
%h1 Listing kites

%table
  %tr
    %th Name
    %th User
    %th
    %th
    %th

  - @kites.each do |kite|
    %tr
      %td= kite.name
      %td= kite.user
      %td= link_to 'Show', kite
      %td= link_to 'Edit', edit_kite_path(kite)
      %td= link_to 'Destroy', kite, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Kite', new_kite_path

app/views/kites/new.html.haml
%h1 New kite

= render 'form'

= link_to 'Back', kites_path

app/views/kites/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @kite.name
%p
  %b User:
  = @kite.user

= link_to 'Edit', edit_kite_path(@kite)
\|
= link_to 'Back', kites_path