config/routes.rb
Sessions::Application.routes.draw do
  resources :locations

  resources :boards

  resources :kites

  resources :sessions

  get "home/index"

  devise_for :users, skip_helpers: true 

  root :to => 'home#index'

end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :user
  has_many :sessions
  
  validates :name, presence: true
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_filter :authenticate_user!
  
  # GET /boards
  # GET /boards.json
  def index
    @boards = current_user.boards.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @boards }
    end
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    @board = current_user.boards.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @board }
    end
  end

  # GET /boards/new
  # GET /boards/new.json
  def new
    @board = current_user.boards.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @board }
    end
  end

  # GET /boards/1/edit
  def edit
    @board = current_user.boards.find(params[:id])
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = current_user.boards.new(params[:board])

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render json: @board, status: :created, location: @board }
      else
        format.html { render action: "new" }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /boards/1
  # PUT /boards/1.json
  def update
    @board = current_user.boards.find(params[:id])

    respond_to do |format|
      if @board.update_attributes(params[:board])
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board = current_user.boards.find(params[:id])
    @board.destroy

    respond_to do |format|
      format.html { redirect_to boards_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/views/boards/_form.html.haml
= form_for @board do |f|
  -if @board.errors.any?
    #error_explanation
      %h2= "#{pluralize(@board.errors.count, "error")} prohibited this board from being saved:"
      %ul
        - @board.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/boards/edit.html.haml
%h1 Editing board

= render 'form'

= link_to 'Show', @board
\|
= link_to 'Back', boards_path

app/views/boards/index.html.haml
%h1 Listing boards

%table
  %tr
    %th Name
    %th User
    %th
    %th
    %th

  - @boards.each do |board|
    %tr
      %td= board.name
      %td= board.user
      %td= link_to 'Show', board
      %td= link_to 'Edit', edit_board_path(board)
      %td= link_to 'Destroy', board, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Board', new_board_path

app/views/boards/new.html.haml
%h1 New board

= render 'form'

= link_to 'Back', boards_path

app/views/boards/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @board.name
%p
  %b User:
  = @board.user

= link_to 'Edit', edit_board_path(@board)
\|
= link_to 'Back', boards_path